version: '3'

services:
  oksanaproject_dev:
    container_name: oksanaproject_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .oksanaproject_dev.env

  oksanaproject_bash:
    container_name: oksanaproject_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .oksanaproject_dev.env

  oksanaproject_test:
    container_name: oksanaproject_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .oksanaproject_dev.env
